vim_config_dir=`pwd`
echo ""
echo ""
echo "Creating symbolic links in home directory ~"
echo "to vim config files in $vim_config_dir"
echo ""
echo ""
cd ~ && ln -s $vim_config_dir/.vimrc .vimrc && echo "Successfully created symbolic link for .vimrc"
cd ~ && ln -s $vim_config_dir/.vim .vim && echo "Successfully created symbolic link for .vim"
echo ""
echo ""
echo "Successfully created all symbolic links for all vim_config_files"
echo ""
echo ""
