echo ""
echo ""
echo "Removing old vim config files..."
echo ""
echo ""
rm -f ~/.vimrc && echo "Successfully removed ~/.vimrc"
rm -f ~/.vim && echo "Successfully removed ~/.vim"
echo ""
echo ""
echo "Successfully removed all old vim config files"
echo ""
echo ""
